List allPets = [
  {
    'name': 'Cat',
    'price': 'Rs. 12,000',
    'image': 'assets/pets/cat1.jpg',
    'sex': 'Male',
    'age': '2 years',
    'isAdopted': false,
  },
  {
    'name': 'Cat',
    'price': 'Rs. 10,000',
    'image': 'assets/pets/cat2.jpg',
    'sex': 'Female',
    'age': '1 year',
    'isAdopted': false,
  },
  {
    'name': 'Cat',
    'price': 'Rs. 8,000',
    'image': 'assets/pets/cat3.jpg',
    'sex': 'Male',
    'age': '5 months',
    'isAdopted': false,
  },
  {
    'name': 'Bird',
    'price': 'Rs. 15,000',
    'image': 'assets/pets/bird1.jpg',
    'sex': 'Male',
    'age': '3 years',
    'isAdopted': true,
  },
  {
    'name': 'Bird',
    'price': 'Rs. 12,000',
    'image': 'assets/pets/bird2.jpg',
    'sex': 'Female',
    'age': '9 months',
    'isAdopted': false,
  },
  {
    'name': 'Bird',
    'price': 'Rs. 7,000',
    'image': 'assets/pets/bird3.jpg',
    'sex': 'Female',
    'age': '1 year',
    'isAdopted': false,
  },
  {
    'name': 'Dog',
    'price': 'Rs. 7,000',
    'image': 'assets/pets/dog1.jpg',
    'sex': 'Male',
    'age': '5 years',
    'isAdopted': false,
  },
  {
    'name': 'Dog',
    'price': 'Rs. 7,000',
    'image': 'assets/pets/dog2.jpg',
    'sex': 'Female',
    'age': '6 years',
    'isAdopted': true,
  },
  {
    'name': 'Dog',
    'price': 'Rs. 9,000',
    'image': 'assets/pets/dog3.jpg',
    'sex': 'Male',
    'age': '2 years',
    'isAdopted': false,
  },
  {
    'name': 'Fish',
    'price': 'Rs.  8,000',
    'image': 'assets/pets/fish1.jpg',
    'sex': 'Female',
    'age': '3 years',
    'isAdopted': false,
  },
  {
    'name': 'Fish',
    'price': 'Rs. 5,600',
    'image': 'assets/pets/fish2.jpg',
    'sex': 'Female',
    'age': '2 years',
    'isAdopted': false,
  },
  {
    'name': 'Fish',
    'price': 'Rs. 14,200',
    'image': 'assets/pets/fish3.jpg',
    'sex': 'Male',
    'age': '4 months',
    'isAdopted': false,
  },
];

List adoptedPets = [
  {
    'name': 'Bird',
    'price': 'Rs. 15,000',
    'image': 'assets/pets/bird1.jpg',
    'sex': 'Male',
    'age': '3 years',
    'isAdopted': true,
  },
  {
    'name': 'Dog',
    'price': 'Rs. 7,000',
    'image': 'assets/pets/dog2.jpg',
    'sex': 'Female',
    'age': '6 years',
    'isAdopted': true,
  },
];
